version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/<dbname>?retryWrites=true&w=majority
    command: ["gunicorn", "--bind", "0.0.0.0:4000", "app:app"]
